### ISSUE TITLE
bad performance of CAN bridge over TCP (on OSX)

### ISSUE THREAD

**Issue by nuft** [cvra/master-firmware#17]

**Comment by antoinealb** [comment]
[Nagle's algorithm](http://en.wikipedia.org/wiki/Nagle's_algorithm) might be a cause. It destroys latency in order to reduce overhead. We should try disabling it and see what it does.

Possible fix for OSX: http://www.shabangs.net/osx/speed-up-macos-x-file-transferring-over-network/

**Comment by nuft** [comment]
The proposed fix for OSX didn't have a visible effect on the latency.
What is strange, is that under Linux it works quite well.

**Comment by antoinealb** [comment]
Hmmm, this is weird. We should try to get packet captures of both linux and OSX clients to see the difference. I can do that tonight if there is a working setup.

**Comment by antoinealb** [comment]
So this is fixed now, right ?

**Comment by nuft** [comment]
The bootloader client works with adjusted timeout settings and the increased buffer size of the bridge, though the weird timing is still there.

**Comment by nuft** [comment]
By making the bootloader protocol more robust, this isn't a critical issue anymore.
