### ISSUE TITLE
memory init of panic log

### ISSUE THREAD

**Issue by Stapelzeiger** [cvra/master-firmware#23]
The panic log doesn't clear the buffer & checksum. This causes the panic to be reported again after a reset.

(Also creating a new memory type in the linker isn't the proper way to have uninitialised memory, a section would be better)

**Comment by antoinealb** [comment]
Hmmm, maybe we should copy the panic log to another location to be able to read it later, then erase .

**Comment by nuft** [comment]
This issue is out of date.
* panic_log buffer is in `.noinit` section now
* old buffer contents are overwritten when a new panic message is logged
