### ISSUE TITLE
Different IP settings dependent on the robot

### ISSUE THREAD

**Issue by antoinealb** [cvra/master-firmware#6]
We need to use a different IP for the two different master boards, but I don't know what would be the best way to change it depending on the host. Basically we have three different options:

1. Change a build define depending on the robot, for example depending on the hostname.
2. Load the settings from the flash of the MCU.
3. Attribute the IP's via DHCP. Each robot would have it's own DHCP server, with different configurations. This is pretty easy to do, since we already got a configuration system for other parts of the embedded Linux.

My personal vote goes for 3. Centralised configurations seems like the way to go for me.

**Comment by Stapelzeiger** [comment]
ok for 3. but we still need a fallback if there is no dhcp server (when connected to a laptop for tests).
Can we easily attribute multiple addresses on the same interface with lwip?

**Comment by antoinealb** [comment]
Nothing is easy with lwip :) what we can maybe do is having a fixed ip that
will be overwritten by dhcp.

Le vendredi 20 mars 2015, Patrick Spieler <notifications@github.com> a
écrit :

**Comment by antoinealb** [comment]
I tried DHCP, but it doesn't work very well, so it will be one `#ifdef` for this year.
