### ISSUE TITLE
Debug mode and panic behaviour

### ISSUE THREAD

**Issue by nuft** [cvra/master-firmware#7]
We should discuss how we add a debug mode where the code blocks on panic. (using a make switch?)
As it is now, the CPU just silently reboots on a fault, which is not helping to debug the code. It should at least indicate a warning with an LED blink pattern.

**Comment by antoinealb** [comment]
It isn't totally silent, the LED turns on. Once the board goes into the robot, we will have more user LEDs and we could turn on a dedicated one.

But agree that it would be useful to hang on fault.

**Comment by antoinealb** [comment]
We switched the panic behaviour to hang + light up all LEDs, so we can attach a debugger.
